<%!

static String[][] insttype = { {"All","All"},
                {"Accelerometer","Accelerometer"},
                {"Anemometer","Anemometer"},
                {"Beta Detector","Beta Detector"},
                {"Camera","Camera"},
                {"Ccd","Ccd"},
                {"Charged Particle Analyzer","Charged Particle Analyzer"},
                {"Detector Array","Detector Array"},
                {"Dosimeter","Dosimeter"},
                {"Dust Impact Detector","Dust Impact Detector"},
                {"Eye","Eye"},
                {"Framing Camera","Framing Camera"},
                {"Gamma-ray Burst Detector","Gamma-ray Burst Detector"},
                {"Gas Detector","Gas Detector"},
                {"Hygrometer","Hygrometer"},
                {"Imaging Camera","Imaging Camera"},
                {"Imaging Spectrometer","Imaging Spectrometer"},
                {"In Situ Meteorology","In Situ Meteorology"},
                {"Infrared Imaging Device","Infrared Imaging Device"},
                {"Infrared Interferometer","Infrared Interferometer"},
                {"Infrared Photometer","Infrared Photometer"},
                {"Infrared Polarimeter","Infrared Polarimeter"},
                {"Infrared Spectrometer","Infrared Spectrometer"},
                {"Laser Altimeter","Laser Altimeter"},
                {"Laser Rangefinder","Laser Rangefinder"},
                {"Linear Array Camera","Linear Array Camera"},
                {"Magnetometer","Magnetometer"},
                {"Mass Spectrometer","Mass Spectrometer"},
                {"Meteorology","Meteorology"},
                {"Nephelometer","Nephelometer"},
                {"Optical Telescope","Optical Telescope"},
                {"Particle Counter","Particle Counter"},
                {"Particle Telescope","Particle Telescope"},
                {"Photometer","Photometer"},
                {"Photopolarimeter","Photopolarimeter"},
                {"Photopolarimeter Radiometer","Photopolarimeter Radiometer"},
                {"Plasma Experiment","Plasma Experiment"},
                {"Plasma Instrument","Plasma Instrument"},
                {"Plasma Wave","Plasma Wave"},
                {"Plasma Wave Spectrometer","Plasma Wave Spectrometer"},
                {"Polarimeter","Polarimeter"},
                {"Quadrupole Mass Spectrometer","Quadrupole Mass Spectrometer"},
                {"Radar","Radar"},
                {"Radar Mapper","Radar Mapper"},
                {"Radio Science","Radio Science"},
                {"Radio Spectrometer","Radio Spectrometer"},
                {"Radiometer","Radiometer"},
                {"Reference Data","Reference Data"},
                {"Spectrograph","Spectrograph"},
                {"Spectrometer","Spectrometer"},
                {"Telescope","Telescope"},
                {"Thermal Infrared Spectrometer","Thermal Infrared Spectrometer"},
                {"Thermistor","Thermistor"},
                {"Ultraviolet Spectrometer","Ultraviolet Spectrometer"},
                {"Unk-xxx","Unk-xxx"},
                {"Vidicon Camera","Vidicon Camera"},
                {"Visual Count","Visual Count"},
                {"Wide Field Camera","Wide Field Camera"}
};


static String[][] dataobjtype = { {"All","All"},
                              {"File","File"},
                              {"Image","Image"},
                              {"Spectral Qube","Spectral Qube"},
                              {"Spectrum","Spectrum"},
                              {"Spice Kernel","Spice Kernel"},
                              {"Table","Table"},
                              {"Time Series","Time Series"}};

static String[][] insthosttype = { {"All","All"},
            {"Earth Based","Earth Based"},
            {"Spacecraft","Spacecraft"}
};

static String[][] archivestat = { {"All", "All"},
                                {"Archived", "Archived"},
                                {"In Lien Resolution", "In Lien Resolution"},
                                {"In Peer Review", "In Peer Review"},
                                {"In Queue", "In Queue"},
                                {"Locally Archived", "Locally Archived"},
                                {"Local Product", "Local Product"},
                                {"Pre Peer Review", "Pre Peer Review"},
                                {"Saved", "Saved"},
                                {"Superseded", "Superseded"}};


%>
