// Copyright 2006-2011, by the California Institute of Technology.
// ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
// Any commercial use must be negotiated with the Office of Technology Transfer
// at the California Institute of Technology.
//
// This software is subject to U. S. export control laws and regulations
// (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
// is subject to U.S. export control laws and regulations, the recipient has
// the responsibility to obtain export licenses or other export authority as
// may be required before exporting such information to foreign countries or
// providing access to foreign nationals.
//
// $Id$

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.05.18 at 11:10:29 AM PDT
//


package gov.nasa.pds.harvest.policy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Candidate complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Candidate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}pds3ProductMetadata" minOccurs="0"/>
 *         &lt;element ref="{}namespace" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}productMetadata" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Candidate", propOrder = {
    "pds3ProductMetadata",
    "namespace",
    "productMetadata"
})
public class Candidate {

    protected Pds3ProductMetadata pds3ProductMetadata;
    protected List<Namespace> namespace;
    protected List<Pds4ProductMetadata> productMetadata;

    /**
     * Gets the value of the pds3ProductMetadata property.
     *
     * @return
     *     possible object is
     *     {@link Pds3ProductMetadata }
     *
     */
    public Pds3ProductMetadata getPds3ProductMetadata() {
        return pds3ProductMetadata;
    }

    /**
     * Sets the value of the pds3ProductMetadata property.
     *
     * @param value
     *     allowed object is
     *     {@link Pds3ProductMetadata }
     *
     */
    public void setPds3ProductMetadata(Pds3ProductMetadata value) {
        this.pds3ProductMetadata = value;
    }

    /**
     * Gets the value of the namespace property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namespace property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamespace().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Namespace }
     *
     *
     */
    public List<Namespace> getNamespace() {
        if (namespace == null) {
            namespace = new ArrayList<Namespace>();
        }
        return this.namespace;
    }

    /**
     * Gets the value of the productMetadata property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productMetadata property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductMetadata().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pds4ProductMetadata }
     *
     *
     */
    public List<Pds4ProductMetadata> getProductMetadata() {
        if (productMetadata == null) {
            productMetadata = new ArrayList<Pds4ProductMetadata>();
        }
        return this.productMetadata;
    }

}
