// Copyright 2006-2010, by the California Institute of Technology.
// ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
// Any commercial use must be negotiated with the Office of Technology Transfer
// at the California Institute of Technology.
//
// This software is subject to U. S. export control laws and regulations
// (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
// is subject to U.S. export control laws and regulations, the recipient has
// the responsibility to obtain export licenses or other export authority as
// may be required before exporting such information to foreign countries or
// providing access to foreign nationals.
//
// $Id$

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2010.10.11 at 08:17:46 AM PDT
//


package gov.nasa.pds.harvest.policy;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the gov.nasa.pds.harvest.policy package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _XPath_QNAME = new QName("", "xPath");

    private static final QName _FilePattern_QNAME =
        new QName("", "filePattern");

    private static final QName _Directories_QNAME =
        new QName("", "directories");
    private static final QName _Bundles_QNAME = new QName("", "bundles");
    private static final QName _File_QNAME = new QName("", "file");
    private static final QName _Path_QNAME = new QName("", "path");
    private static final QName _Policy_QNAME = new QName("", "policy");

    private static final QName _ProductMetadata_QNAME =
        new QName("", "productMetadata");

    private static final QName _Collections_QNAME =
        new QName("", "collections");

    private static final QName _Namespace_QNAME = new QName("", "namespace");

    private static final QName _Candidates_QNAME =
        new QName("", "candidates");

    /**
     * Create a new ObjectFactory that can be used to create new instances
     * of schema derived classes for package: gov.nasa.pds.harvest.policy
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Bundle }
     *
     */
    public Bundle createBundle() {
        return new Bundle();
    }

    /**
     * Create an instance of {@link Namespace }
     *
     */
    public Namespace createNamespace() {
        return new Namespace();
    }

    /**
     * Create an instance of {@link Directory }
     *
     */
    public Directory createDirectory() {
        return new Directory();
    }

    /**
     * Create an instance of {@link Candidate }
     *
     */
    public Candidate createCandidate() {
        return new Candidate();
    }

    /**
     * Create an instance of {@link ProductMetadata }
     *
     */
    public ProductMetadata createProductMetadata() {
        return new ProductMetadata();
    }

    /**
     * Create an instance of {@link Policy }
     *
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link Collection }
     *
     */
    public Collection createCollection() {
        return new Collection();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "xPath")
    public JAXBElement<String> createXPath(String value) {
        return new JAXBElement<String>(_XPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "filePattern")
    public JAXBElement<String> createFilePattern(String value) {
        return new JAXBElement<String>(_FilePattern_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Directory }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "directories")
    public JAXBElement<Directory> createDirectories(Directory value) {
        return new JAXBElement<Directory>(_Directories_QNAME,
                Directory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Bundle }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "bundles")
    public JAXBElement<Bundle> createBundles(Bundle value) {
        return new JAXBElement<Bundle>(_Bundles_QNAME, Bundle.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "file")
    public JAXBElement<String> createFile(String value) {
        return new JAXBElement<String>(_File_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "path")
    public JAXBElement<String> createPath(String value) {
        return new JAXBElement<String>(_Path_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Policy }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "policy")
    public JAXBElement<Policy> createPolicy(Policy value) {
        return new JAXBElement<Policy>(_Policy_QNAME, Policy.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductMetadata }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "productMetadata")
    public JAXBElement<ProductMetadata> createProductMetadata(ProductMetadata value) {
        return new JAXBElement<ProductMetadata>(_ProductMetadata_QNAME,
                ProductMetadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Collection }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "collections")
    public JAXBElement<Collection> createCollections(Collection value) {
        return new JAXBElement<Collection>(_Collections_QNAME,
                Collection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Namespace }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "namespace")
    public JAXBElement<Namespace> createNamespace(Namespace value) {
        return new JAXBElement<Namespace>(_Namespace_QNAME,
                Namespace.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Candidate }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "candidates")
    public JAXBElement<Candidate> createCandidates(Candidate value) {
        return new JAXBElement<Candidate>(_Candidates_QNAME, Candidate.class,
                null, value);
    }

}
