// Copyright 2006-2010, by the California Institute of Technology.
// ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
// Any commercial use must be negotiated with the Office of Technology Transfer
// at the California Institute of Technology.
//
// This software is subject to U. S. export control laws and regulations
// (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
// is subject to U.S. export control laws and regulations, the recipient has
// the responsibility to obtain export licenses or other export authority as
// may be required before exporting such information to foreign countries or
// providing access to foreign nationals.
//
// $Id$

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2010.10.11 at 08:17:46 AM PDT
//


package gov.nasa.pds.harvest.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Policy complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 *  within this class.
 *
 * <pre>
 * &lt;complexType name="Policy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}bundles" minOccurs="0"/>
 *         &lt;element ref="{}collections" minOccurs="0"/>
 *         &lt;element ref="{}directories" minOccurs="0"/>
 *         &lt;element ref="{}candidates"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Policy", propOrder = {
    "bundles",
    "collections",
    "directories",
    "candidates"
})
public class Policy {

    protected Bundle bundles;
    protected Collection collections;
    protected Directory directories;
    @XmlElement(required = true)
    protected Candidate candidates;

    public Policy() {
        directories = new Directory();
        bundles = new Bundle();
        collections = new Collection();
    }

    /**
     * Merges 2 policy files together.
     *
     * @param policy A policy file.
     */
    public void add(Policy policy) {
        for (String path : policy.getDirectories().getPath()) {
                directories.getPath().add(path);
        }
        for (String pattern : policy.getDirectories().getFilePattern()) {
                directories.getPath().add(pattern);
        }
        for (String file : policy.getBundles().getFile()) {
                bundles.getFile().add(file);
        }
        for (String file : policy.getBundles().getFile()) {
            collections.getFile().add(file);
    }
        this.candidates.getNamespace().addAll(
                policy.getCandidates().getNamespace());

        this.candidates.getProductMetadata().addAll(
                policy.getCandidates().getProductMetadata());
    }

    /**
     * Gets the value of the bundles property.
     *
     * @return
     *     possible object is
     *     {@link Bundle }
     *
     */
    public Bundle getBundles() {
        return bundles;
    }

    /**
     * Sets the value of the bundles property.
     *
     * @param value
     *     allowed object is
     *     {@link Bundle }
     *
     */
    public void setBundles(Bundle value) {
        this.bundles = value;
    }

    /**
     * Gets the value of the collections property.
     *
     * @return
     *     possible object is
     *     {@link Collection }
     *
     */
    public Collection getCollections() {
        return collections;
    }

    /**
     * Sets the value of the collections property.
     *
     * @param value
     *     allowed object is
     *     {@link Collection }
     *
     */
    public void setCollections(Collection value) {
        this.collections = value;
    }

    /**
     * Gets the value of the directories property.
     *
     * @return
     *     possible object is
     *     {@link Directory }
     *
     */
    public Directory getDirectories() {
        return directories;
    }

    /**
     * Sets the value of the directories property.
     *
     * @param value
     *     allowed object is
     *     {@link Directory }
     *
     */
    public void setDirectories(Directory value) {
        this.directories = value;
    }

    /**
     * Gets the value of the candidates property.
     *
     * @return
     *     possible object is
     *     {@link Candidate }
     *
     */
    public Candidate getCandidates() {
        return candidates;
    }

    /**
     * Sets the value of the candidates property.
     *
     * @param value
     *     allowed object is
     *     {@link Candidate }
     *
     */
    public void setCandidates(Candidate value) {
        this.candidates = value;
    }

}
