// Copyright 2006-2010, by the California Institute of Technology.
// ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
// Any commercial use must be negotiated with the Office of Technology Transfer
// at the California Institute of Technology.
//
// This software is subject to U. S. export control laws and regulations
// (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
// is subject to U.S. export control laws and regulations, the recipient has
// the responsibility to obtain export licenses or other export authority as
// may be required before exporting such information to foreign countries or
// providing access to foreign nationals.
//
// $Id$

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.09.23 at 10:34:07 AM PDT
//


package gov.nasa.pds.harvest.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Policy complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Policy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}rootDirectories" minOccurs="0"/>
 *         &lt;element ref="{}inventoryFiles" minOccurs="0"/>
 *         &lt;element ref="{}candidates"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Policy", propOrder = {
    "rootDirectories",
    "inventoryFiles",
    "candidates"
})
public class Policy {

    protected RootDirectory rootDirectories;
    protected InventoryFile inventoryFiles;
    @XmlElement(required = true)
    protected Candidate candidates;

public Policy() {
    	rootDirectories = new RootDirectory();
    	inventoryFiles = new InventoryFile();
    }

    public void add(Policy policy) {
    	for(String location : policy.getRootDirectories().getLocation()) {
    		rootDirectories.getLocation().add(location);
    	}
    	for(String pattern : policy.getRootDirectories().getFilePattern()) {
    		rootDirectories.getLocation().add(pattern);
    	}
    	for(String location : policy.getInventoryFiles().getLocation()) {
    		inventoryFiles.getLocation().add(location);
    	}
    	this.candidates.getNamespace().addAll(policy.getCandidates().getNamespace());
    	this.candidates.getProductMetadata().addAll(policy.getCandidates().getProductMetadata());
    }
    /**
     * Gets the value of the rootDirectories property.
     *
     * @return
     *     possible object is
     *     {@link RootDirectory }
     *
     */
    public RootDirectory getRootDirectories() {
        return rootDirectories;
    }

    /**
     * Sets the value of the rootDirectories property.
     *
     * @param value
     *     allowed object is
     *     {@link RootDirectory }
     *
     */
    public void setRootDirectories(RootDirectory value) {
        this.rootDirectories = value;
    }

    /**
     * Gets the value of the inventoryFiles property.
     *
     * @return
     *     possible object is
     *     {@link InventoryFile }
     *
     */
    public InventoryFile getInventoryFiles() {
        return inventoryFiles;
    }

    /**
     * Sets the value of the inventoryFiles property.
     *
     * @param value
     *     allowed object is
     *     {@link InventoryFile }
     *
     */
    public void setInventoryFiles(InventoryFile value) {
        this.inventoryFiles = value;
    }

    /**
     * Gets the value of the candidates property.
     *
     * @return
     *     possible object is
     *     {@link Candidate }
     *
     */
    public Candidate getCandidates() {
        return candidates;
    }

    /**
     * Sets the value of the candidates property.
     *
     * @param value
     *     allowed object is
     *     {@link Candidate }
     *
     */
    public void setCandidates(Candidate value) {
        this.candidates = value;
    }

}
