#! /bin/bash

USERS="`ls src/main/webapp/projects`"

for u in $USERS; do

USER_NAME=`grep 'user\.id' "src/main/webapp/projects/$u/user.properties" | awk '-F *= *' '{print $2}'`

echo $USER_NAME

done
