#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: `basename $0` userid"
    exit 1
fi

USERS="`ls src/main/webapp/projects`"
USER_DIR=""

for u in $USERS; do

USER_NAME=`grep 'user\.id' "src/main/webapp/projects/$u/user.properties" | awk '-F *= *' '{print $2}'`

if [ "$USER_NAME" = "$1" ]; then
    USER_DIR="src/main/webapp/projects/$u"
fi

done

if [ -z "$USER_DIR" ]; then
    echo "Cannot find user $1"
    exit 2
fi

for item in `find "$USER_DIR/projects" -name item.properties`; do

ITEM_DIR=`echo $item | sed -e 's;/item\.properties;;'`
ITEM_NAME=`grep 'item.name' $item | awk '-F *= *' '{print $2}'`

echo "$ITEM_NAME - $ITEM_DIR"

done
