// Copyright 2006-2012, by the California Institute of Technology.
// ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
// Any commercial use must be negotiated with the Office of Technology Transfer
// at the California Institute of Technology.
//
// This software is subject to U. S. export control laws and regulations
// (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
// is subject to U.S. export control laws and regulations, the recipient has
// the responsibility to obtain export licenses or other export authority as
// may be required before exporting such information to foreign countries or
// providing access to foreign nationals.
//
// $Id$

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.18 at 08:01:29 AM PDT
//


package gov.nasa.pds.harvest.pdap.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}pdsRegistry" minOccurs="0"/>
 *         &lt;element ref="{}pdapServices" minOccurs="0"/>
 *         &lt;element ref="{}productMetadata" minOccurs="0"/>
 *         &lt;element ref="{}resourceMetadata"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "policy")
public class Policy {

    protected PdsRegistry pdsRegistry;
    protected PdapServices pdapServices;
    protected ProductMetadata productMetadata;
    @XmlElement(required = true)
    protected ResourceMetadata resourceMetadata;

    public Policy() {
      pdsRegistry = new PdsRegistry();
      pdapServices = new PdapServices();
      productMetadata = new ProductMetadata();
      resourceMetadata = new ResourceMetadata();
    }

    /**
     * Gets the value of the pdsRegistry property.
     *
     * @return
     *     possible object is
     *     {@link PdsRegistry }
     *
     */
    public PdsRegistry getPdsRegistry() {
        return pdsRegistry;
    }

    /**
     * Sets the value of the pdsRegistry property.
     *
     * @param value
     *     allowed object is
     *     {@link PdsRegistry }
     *
     */
    public void setPdsRegistry(PdsRegistry value) {
        this.pdsRegistry = value;
    }

    /**
     * Gets the value of the pdapServices property.
     *
     * @return
     *     possible object is
     *     {@link PdapServices }
     *
     */
    public PdapServices getPdapServices() {
        return pdapServices;
    }

    /**
     * Sets the value of the pdapServices property.
     *
     * @param value
     *     allowed object is
     *     {@link PdapServices }
     *
     */
    public void setPdapServices(PdapServices value) {
        this.pdapServices = value;
    }

    /**
     * Gets the value of the productMetadata property.
     *
     * @return
     *     possible object is
     *     {@link ProductMetadata }
     *
     */
    public ProductMetadata getProductMetadata() {
        return productMetadata;
    }

    /**
     * Sets the value of the productMetadata property.
     *
     * @param value
     *     allowed object is
     *     {@link ProductMetadata }
     *
     */
    public void setProductMetadata(ProductMetadata value) {
        this.productMetadata = value;
    }

    /**
     * Gets the value of the resourceMetadata property.
     *
     * @return
     *     possible object is
     *     {@link ResourceMetadata }
     *
     */
    public ResourceMetadata getResourceMetadata() {
        return resourceMetadata;
    }

    /**
     * Sets the value of the resourceMetadata property.
     *
     * @param value
     *     allowed object is
     *     {@link ResourceMetadata }
     *
     */
    public void setResourceMetadata(ResourceMetadata value) {
        this.resourceMetadata = value;
    }

}
