// Copyright 2006-2012, by the California Institute of Technology.
// ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
// Any commercial use must be negotiated with the Office of Technology Transfer
// at the California Institute of Technology.
//
// This software is subject to U. S. export control laws and regulations
// (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
// is subject to U.S. export control laws and regulations, the recipient has
// the responsibility to obtain export licenses or other export authority as
// may be required before exporting such information to foreign countries or
// providing access to foreign nationals.
//
// $Id$

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.18 at 08:01:29 AM PDT
//


package gov.nasa.pds.harvest.pdap.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductMetadata complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ProductMetadata">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}staticMetadata" minOccurs="0"/>
 *         &lt;element ref="{}dynamicMetadata" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductMetadata", propOrder = {

})
public class ProductMetadata {

    protected StaticMetadata staticMetadata;
    protected DynamicMetadata dynamicMetadata;

    public ProductMetadata() {
      staticMetadata = new StaticMetadata();
      dynamicMetadata = new DynamicMetadata();
    }

    /**
     * Gets the value of the staticMetadata property.
     *
     * @return
     *     possible object is
     *     {@link StaticMetadata }
     *
     */
    public StaticMetadata getStaticMetadata() {
        return staticMetadata;
    }

    /**
     * Sets the value of the staticMetadata property.
     *
     * @param value
     *     allowed object is
     *     {@link StaticMetadata }
     *
     */
    public void setStaticMetadata(StaticMetadata value) {
        this.staticMetadata = value;
    }

    /**
     * Gets the value of the dynamicMetadata property.
     *
     * @return
     *     possible object is
     *     {@link DynamicMetadata }
     *
     */
    public DynamicMetadata getDynamicMetadata() {
        return dynamicMetadata;
    }

    /**
     * Sets the value of the dynamicMetadata property.
     *
     * @param value
     *     allowed object is
     *     {@link DynamicMetadata }
     *
     */
    public void setDynamicMetadata(DynamicMetadata value) {
        this.dynamicMetadata = value;
    }

}
