// Copyright 2006-2012, by the California Institute of Technology.
// ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
// Any commercial use must be negotiated with the Office of Technology Transfer
// at the California Institute of Technology.
//
// This software is subject to U. S. export control laws and regulations
// (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
// is subject to U.S. export control laws and regulations, the recipient has
// the responsibility to obtain export licenses or other export authority as
// may be required before exporting such information to foreign countries or
// providing access to foreign nationals.
//
// $Id$

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.09.10 at 03:41:38 PM PDT
//


package gov.nasa.pds.harvest.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Checksums complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Checksums">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}manifest" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}generate"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Checksums", propOrder = {
    "manifest"
})
public class Checksums {

    protected String manifest;
    @XmlAttribute
    protected Boolean generate;

    /**
     * Gets the value of the manifest property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getManifest() {
        return manifest;
    }

    /**
     * Sets the value of the manifest property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setManifest(String value) {
        this.manifest = value;
    }

    /**
     * Gets the value of the generate property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isGenerate() {
        if (generate == null) {
            return false;
        } else {
            return generate;
        }
    }

    /**
     * Sets the value of the generate property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setGenerate(Boolean value) {
        this.generate = value;
    }

}
