// Copyright 2006-2013, by the California Institute of Technology.
// ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
// Any commercial use must be negotiated with the Office of Technology Transfer
// at the California Institute of Technology.
//
// This software is subject to U. S. export control laws and regulations
// (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
// is subject to U.S. export control laws and regulations, the recipient has
// the responsibility to obtain export licenses or other export authority as
// may be required before exporting such information to foreign countries or
// providing access to foreign nationals.
//
// $Id$

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.01.16 at 08:20:27 AM PST
//


package gov.nasa.pds.harvest.policy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Directory complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Directory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}path" maxOccurs="unbounded"/>
 *         &lt;element ref="{}fileFilter" minOccurs="0"/>
 *         &lt;element ref="{}directoryFilter" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Directory", propOrder = {
    "path",
    "fileFilter",
    "directoryFilter"
})
public class Directory {

    @XmlElement(required = true)
    protected List<String> path;
    protected FileFilter fileFilter;
    protected DirectoryFilter directoryFilter;

    /**
     * Gets the value of the path property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the path property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPath().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getPath() {
        if (path == null) {
            path = new ArrayList<String>();
        }
        return this.path;
    }

    /**
     * Gets the value of the fileFilter property.
     *
     * @return
     *     possible object is
     *     {@link FileFilter }
     *
     */
    public FileFilter getFileFilter() {
      if (fileFilter == null) {
        fileFilter = new FileFilter();
      }
      return this.fileFilter;
    }

    /**
     * Sets the value of the fileFilter property.
     *
     * @param value
     *     allowed object is
     *     {@link FileFilter }
     *
     */
    public void setFileFilter(FileFilter value) {
        this.fileFilter = value;
    }

    /**
     * Gets the value of the directoryFilter property.
     *
     * @return
     *     possible object is
     *     {@link DirectoryFilter }
     *
     */
    public DirectoryFilter getDirectoryFilter() {
      if (directoryFilter == null) {
        directoryFilter = new DirectoryFilter();
      }
      return this.directoryFilter;
    }

    /**
     * Sets the value of the directoryFilter property.
     *
     * @param value
     *     allowed object is
     *     {@link DirectoryFilter }
     *
     */
    public void setDirectoryFilter(DirectoryFilter value) {
        this.directoryFilter = value;
    }

}
