// Copyright 2006-2011, by the California Institute of Technology.
// ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
// Any commercial use must be negotiated with the Office of Technology Transfer
// at the California Institute of Technology.
//
// This software is subject to U. S. export control laws and regulations
// (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
// is subject to U.S. export control laws and regulations, the recipient has
// the responsibility to obtain export licenses or other export authority as
// may be required before exporting such information to foreign countries or
// providing access to foreign nationals.
//
// $Id$

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.08.05 at 04:13:43 PM PDT
//


package gov.nasa.pds.harvest.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pds3ProductMetadata complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Pds3ProductMetadata">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}lidPrefix" minOccurs="0"/>
 *         &lt;element ref="{}associations" minOccurs="0"/>
 *         &lt;element ref="{}ancillaryMetadata" minOccurs="0"/>
 *         &lt;element ref="{}includePaths" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pds3ProductMetadata", propOrder = {

})
public class Pds3ProductMetadata {

    protected String lidPrefix;
    protected Associations associations;
    protected AncillaryMetadata ancillaryMetadata;
    protected IncludePath includePaths;

    /**
     * Gets the value of the lidPrefix property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLidPrefix() {
        return lidPrefix;
    }

    /**
     * Sets the value of the lidPrefix property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLidPrefix(String value) {
        this.lidPrefix = value;
    }

    /**
     * Gets the value of the associations property.
     *
     * @return
     *     possible object is
     *     {@link Associations }
     *
     */
    public Associations getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     *
     * @param value
     *     allowed object is
     *     {@link Associations }
     *
     */
    public void setAssociations(Associations value) {
        this.associations = value;
    }

    /**
     * Gets the value of the ancillaryMetadata property.
     *
     * @return
     *     possible object is
     *     {@link AncillaryMetadata }
     *
     */
    public AncillaryMetadata getAncillaryMetadata() {
        return ancillaryMetadata;
    }

    /**
     * Sets the value of the ancillaryMetadata property.
     *
     * @param value
     *     allowed object is
     *     {@link AncillaryMetadata }
     *
     */
    public void setAncillaryMetadata(AncillaryMetadata value) {
        this.ancillaryMetadata = value;
    }

    /**
     * Gets the value of the includePaths property.
     *
     * @return
     *     possible object is
     *     {@link IncludePath }
     *
     */
    public IncludePath getIncludePaths() {
        if (includePaths == null) {
          return new IncludePath();
        } else {
          return includePaths;
        }
    }

    /**
     * Sets the value of the includePaths property.
     *
     * @param value
     *     allowed object is
     *     {@link IncludePath }
     *
     */
    public void setIncludePaths(IncludePath value) {
        this.includePaths = value;
    }

}
