// Copyright 2006-2013, by the California Institute of Technology.
// ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
// Any commercial use must be negotiated with the Office of Technology Transfer
// at the California Institute of Technology.
//
// This software is subject to U. S. export control laws and regulations
// (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
// is subject to U.S. export control laws and regulations, the recipient has
// the responsibility to obtain export licenses or other export authority as
// may be required before exporting such information to foreign countries or
// providing access to foreign nationals.
//
// $Id$

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.04 at 10:56:08 AM PST
//


package gov.nasa.pds.harvest.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pds3ProductMetadata complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Pds3ProductMetadata">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}lidContents"/>
 *         &lt;element ref="{}titleContents"/>
 *         &lt;element ref="{}staticMetadata" minOccurs="0"/>
 *         &lt;element ref="{}ancillaryMetadata" minOccurs="0"/>
 *         &lt;element ref="{}includePaths" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pds3ProductMetadata", propOrder = {

})
public class Pds3ProductMetadata {

    @XmlElement(required = true)
    protected LidContents lidContents;
    @XmlElement(required = true)
    protected TitleContents titleContents;
    protected StaticMetadata staticMetadata;
    protected AncillaryMetadata ancillaryMetadata;
    protected IncludePath includePaths;

    public Pds3ProductMetadata() {
      lidContents = new LidContents();
      titleContents = new TitleContents();
      staticMetadata = new StaticMetadata();
      ancillaryMetadata = new AncillaryMetadata();
      includePaths = new IncludePath();
    }

    /**
     * Gets the value of the lidContents property.
     *
     * @return
     *     possible object is
     *     {@link LidContents }
     *
     */
    public LidContents getLidContents() {
        return lidContents;
    }

    /**
     * Sets the value of the lidContents property.
     *
     * @param value
     *     allowed object is
     *     {@link LidContents }
     *
     */
    public void setLidContents(LidContents value) {
        this.lidContents = value;
    }

    /**
     * Gets the value of the titleContents property.
     *
     * @return
     *     possible object is
     *     {@link TitleContents }
     *
     */
    public TitleContents getTitleContents() {
        return titleContents;
    }

    /**
     * Sets the value of the titleContents property.
     *
     * @param value
     *     allowed object is
     *     {@link TitleContents }
     *
     */
    public void setTitleContents(TitleContents value) {
        this.titleContents = value;
    }

    /**
     * Gets the value of the staticMetadata property.
     *
     * @return
     *     possible object is
     *     {@link StaticMetadata }
     *
     */
    public StaticMetadata getStaticMetadata() {
        return staticMetadata;
    }

    /**
     * Sets the value of the staticMetadata property.
     *
     * @param value
     *     allowed object is
     *     {@link StaticMetadata }
     *
     */
    public void setStaticMetadata(StaticMetadata value) {
        this.staticMetadata = value;
    }

    /**
     * Gets the value of the ancillaryMetadata property.
     *
     * @return
     *     possible object is
     *     {@link AncillaryMetadata }
     *
     */
    public AncillaryMetadata getAncillaryMetadata() {
        return ancillaryMetadata;
    }

    /**
     * Sets the value of the ancillaryMetadata property.
     *
     * @param value
     *     allowed object is
     *     {@link AncillaryMetadata }
     *
     */
    public void setAncillaryMetadata(AncillaryMetadata value) {
        this.ancillaryMetadata = value;
    }

    /**
     * Gets the value of the includePaths property.
     *
     * @return
     *     possible object is
     *     {@link IncludePath }
     *
     */
    public IncludePath getIncludePaths() {
        return includePaths;
    }

    /**
     * Sets the value of the includePaths property.
     *
     * @param value
     *     allowed object is
     *     {@link IncludePath }
     *
     */
    public void setIncludePaths(IncludePath value) {
        this.includePaths = value;
    }

}
